language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.4

matrix:
  include:
  - php: 7.4
    env: COMPOSER_FLAGS="--prefer-lowest"

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

#install:
#  - composer update  ${COMPOSER_FLAGS} --no-interaction

script:
  # - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/bin/phpunit